CREATE TABLE PERSONA (
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50)
);

INSERT INTO PERSONA VALUES (1, 'Ana Torres');
INSERT INTO PERSONA VALUES (2, 'Carlos Ruiz');
INSERT INTO PERSONA VALUES (3, 'María López');
INSERT INTO PERSONA VALUES (4, 'Juan Pérez');
INSERT INTO PERSONA VALUES (5, 'Laura Gómez');
INSERT INTO PERSONA VALUES (6, 'Pedro Martínez');
INSERT INTO PERSONA VALUES (7, 'Sofía Rodríguez');
INSERT INTO PERSONA VALUES (8, 'Andrés Herrera');
INSERT INTO PERSONA VALUES (9, 'Paula Ramírez');
INSERT INTO PERSONA VALUES (10, 'Diego Castillo');
INSERT INTO PERSONA VALUES (11, 'Lucía Morales');
INSERT INTO PERSONA VALUES (12, 'Jorge Silva');
INSERT INTO PERSONA VALUES (13, 'Valentina Rojas');
INSERT INTO PERSONA VALUES (14, 'Felipe Ortiz');
INSERT INTO PERSONA VALUES (15, 'Camila Vargas');
INSERT INTO PERSONA VALUES (16, 'Miguel Suárez');
INSERT INTO PERSONA VALUES (17, 'Natalia Pineda');
INSERT INTO PERSONA VALUES (18, 'Sebastián León');
INSERT INTO PERSONA VALUES (19, 'Daniela Cruz');
INSERT INTO PERSONA VALUES (20, 'Ricardo Mejía');

COMMIT;